In [1]:
import numpy as np 
import pandas as pd

In [4]:
# Loading The DATASET : 

df = pd.read_csv("trade.csv") 
df

,country_or_area,year,comm_code,commodity,flow,trade_usd,weight_kg,quantity_name,quantity,category
0,Australia,2016,10111,"Horses, live pure-bred breeding",Export,128577553,900450.0,Number of items,1882.0,01_live_animals
1,Australia,2016,10119,"Horses, live except pure-bred breeding",Re-Import,4928989,47240.0,Number of items,104.0,01_live_animals
2,Australia,2016,10119,"Horses, live except pure-bred breeding",Export,11812782,153587.0,Number of items,276.0,01_live_animals
3,Australia,2016,10119,"Horses, live except pure-bred breeding",Import,90430302,1082493.0,Number of items,2073.0,01_live_animals
4,Australia,2016,10120,"Asses, mules and hinnies, live",Export,58473,5805.0,Number of items,416.0,01_live_animals
...,...,...,...,...,...,...,...,...,...,...
59085,Canada,1989,121300,"Cereal straw & husks, unprepared",Export,19193,151000.0,Weight in kilograms,151000.0,12_oil_seed_oleagic_fruits_grain_seed_fruit_et...
59086,Canada,1989,121410,Lucerne (alfalfa) meal and pellets,Import,42016,220003.0,Weight in kilograms,220003.0,12_oil_seed_oleagic_fruits_grain_seed_fruit_et...
59087,Canada,1989,121410,Lucerne (alfalfa) meal and pellets,Export,62521781,448829618.0,Weight in kilograms,448829618.0,12_oil_seed_oleagic_fruits_grain_seed_fruit_et...
59088,Canada,1989,121490,"Other fodder and forage products, roots, etc.",Import,9176645,89547000.0,Weight in kilograms,89547000.0,12_oil_seed_oleagic_fruits_grain_seed_fruit_et...
59089,Canada,1989,121490,"Other fodder and forage products, roots, etc.",Export,20603601,155491000.0,Weight in kilograms,155491000.0,12_oil_seed_oleagic_fruits_grain_seed_fruit_et...

In [6]:
top_2000_rows = df.head(2000) 
top_2000_rows.to_csv("trade1.csv", index = False)